package com.crazymike.util;

/**
 * Created by cuber on 2015/10/23.
 */
public enum PreferencesKey {
    TODAY, IS_DEVEL, PHPSESSID, GCM_TOKE, CUE_SHEET, MEMBER_ID, SHOW_NOTIFICATION_ID, LOGIN_TYPE, LOGIN_USER, LAST_PUSH, TERMINAL_SERVICE_TIME_START, TERMINAL_SERVICE_TIME_END
}
